### ISSUE TITLE
Apply Mandalorion-Episode-II in regular ONT 1D data

### ISSUE THREAD

**Issue by fantastycrane** [rvolden/Mandalorion-Episode-II#2]
Hi @rvolden ,

It says in README that current Mandalorion only supports data format C3POa produces from R2C2 nanopore data.  Is there any way I can modify the scripts or my data to make Mandalorion available for ONT 1D data? For example, is it feasible to edit sequence id in my fasta/fastq file to the same format as C3POa produces?

**Comment by rvolden** [comment]
We have this implemented [here](https://github.com/christopher-vollmers/Mandalorion-Episode-II). Take precaution as this is experimental. Hopefully this works out for you.

**Comment by Joon-20** [comment]
Hi @rvolden,

I tried with my ONT 1D data and got this error. I think this topic is relevant to what fantastycrane asked, but if you disagree, I will re-post it. 

I prepared all the files (fasta/fastq/SAM/psl) according to the instructions. When I ran the defineAndQuantifyWrapper.py with the same parameters you used as an example, I got the error messages as below.

Traceback (most recent call last):
  File "spliceSites.py", line 510, in <module>
    chromosome_list, histo_coverage = collect_reads(content_file)
  File "spliceSites.py", line 276, in collect_reads
    coverage = int(name.split('_')[3])
IndexError: list index out of range

Can you take a look to see what went wrong?
Thank you!

**Comment by fantastycrane** [comment]
Hi @rvolden ,

Thanks for the reply. I will try it with my ONT 1D data.


Hi  @Joon-Biogen ,

I believe you are using the wrong version of Mandalorion-Episode-II.  What you are using might still be the version that only supports data format C3POa produces. The appropriate version is the one indicated by the link in rvolden's reply, which is under christopher-vollmers' repo.

**Comment by Joon-20** [comment]
Hi @fantastycrane ,

Thank you! I missed that there are different versions.
