### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by jchang97** [rvolden/Mandalorion-Episode-II#3]
Hi there,

I am trying to quantify my ONT DRS reads with Mandalorion - II.
However, I'm getting this error: 

ValueError: invalid literal for int() with base 10: '/media/gsfl/Jessie/First_Run/'

Please let me know why this is happening.

Thank you
Jessie

**Comment by rvolden** [comment]
Can you provide some more information? Like what command you used to run Mandalorion? It looks like you're giving a non-int to a command line option that's supposed to be an int.

As a side note, this version of Mandalorion isn't really designed to work with DRS, but instead with R2C2 consensus reads.

**Comment by jchang97** [comment]
Yes, I understand that it's designed for R2C2 consensus reads but I'm sort of trying it out just in case it works!

I have attached an image of the command I used.

![mandalorion](https://user-images.githubusercontent.com/41040156/45523687-b6c9ac80-b81e-11e8-965a-fefa261d0d37.png)

Thank you
Jessie

**Comment by rvolden** [comment]
You're trying to run the wrong script. I know the names are kind of similar, so that's my bad. You should be trying to run the wrapper script instead of defineAndQuantifyIsoforms.py. The one you're trying to run will be run by the wrapper script.

**Comment by jchang97** [comment]
Hi, sorry for bothering again but with the wrapper script this error comes through. 

![capture](https://user-images.githubusercontent.com/41040156/45591595-8cf1c080-b9ab-11e8-8dac-b194da3b3bfa.PNG)

**Comment by rvolden** [comment]
It looks like your content file isn't encoded properly. Make sure it's utf-8 encoded so that python can read it
