### ISSUE TITLE
Issue with the run

### ISSUE THREAD

**Issue by ljw90607** [rvolden/Mandalorion-Episode-II#4]
Dear developer,

Hello. First of all, thank you for creating such wonderful tool.
I was trying to run the script you have provided and ended up getting some technical issue.

The script I typed in was shown below:
`
python3 /data/ONT_RNA/download/mandalorion/Mandalorion-Episode-II-master/defineAndQuantifyWrapper.py -c 20180918_PM_AU_samples.txt -f contig_file.txt -p /data/ONT_RNA/download/mandalorion/Mandalorion-Episode-II-master/ -m /data/ONT_RNA/download/mandalorion/Mandalorion-Episode-II-master/NUC.4.4.mat -u 5 -d 30 -s 200 -g /data/ONT_RNA/reference/gencode.v28.annotation.gtf -r 0.05 -R 3 -i 0 -t 0 -I 100 -T 60
`

and the result error was shown as below:
`
python3: can't open file 'spliceSites.py': [Errno 2] No such file or directory
python3: can't open file 'defineAndQuantifyIsoforms.py': [Errno 2] No such file or directory
python3: can't open file 'createConsensi.py': [Errno 2] No such file or directory
python3: can't open file 'filterIsoforms.py': [Errno 2] No such file or directory`

I was not quite sure if any installation was needed for these python scripts to run.
Please let me know if any further information needed for troubleshooting.

Thank you very much for your help.

Jungwoo

**Comment by rvolden** [comment]
There shouldn't be any installation needed for this to work. It isn't finding the rest of the scripts because you aren't running from the Mandalorion directory. Try changing directories and rerun

**Comment by ljw90607** [comment]
Thank you for your help!
I tried another run in the Mandalorion directory and here's the issue that I ran into.
Since I was not able to find the example files to run, I was not quite sure what to fix from this error message below.

Traceback (most recent call last):
  File "spliceSites.py", line 510, in <module>
    chromosome_list, histo_coverage = collect_reads(content_file)
  File "spliceSites.py", line 276, in collect_reads
    coverage = int(name.split('_')[3])
IndexError: list index out of range
['/data/ONT_RNA/Data/PM-AU-0002-N-A1/20180817_colon_2N_minimap2.psl', '/data/ONT_RNA/Data/PM-AU-0002-N-A1/20180817_colon_2N.fasta', '/data/ONT_RNA/analysis/', '/data/ONT_RNA/Data/PM-AU-0002-N-A1/20180817_colon_2N.fastq']
mkdir: cannot create directory `/data/ONT_RNA/analysis//parsed_reads': File exists
rm: cannot remove `/data/ONT_RNA/analysis//parsed_reads/*': No such file or directory
Traceback (most recent call last):
  File "defineAndQuantifyIsoforms.py", line 231, in <module>
    main()
  File "defineAndQuantifyIsoforms.py", line 225, in main
    splice_dict = splice_dict = collect_splice_events(path)
  File "defineAndQuantifyIsoforms.py", line 33, in collect_splice_events
    for line in open(path + '/SS.bed'):
FileNotFoundError: [Errno 2] No such file or directory: '/data/ONT_RNA/download/mandalorion/Mandalorion-Episode-II-master///SS.bed'
Using consensus from your path, not the config file.
Using poa from your path, not the config file.
Using blat from your path, not the config file.
Using water from your path, not the config file.
Traceback (most recent call last):
  File "createConsensi.py", line 215, in <module>
    for line in open(path + '/isoform_list'):
FileNotFoundError: [Errno 2] No such file or directory: '/data/ONT_RNA/analysis//isoform_list'


I really appreciate for you helping me with this issue.

**Comment by rvolden** [comment]
Looks like you're trying to use RNA data instead of R2C2 reads. There's supposed to be a portion of the read name that indicates the coverage. Mandalorion isn't designed to work with RNA reads

**Comment by ljw90607** [comment]
Thank you for your comment. 
I am actually working with cDNA data (but labeled them as RNA.), but the library was prepared with typical nanopore cDNA-PCR method. Would this dataset still work? 
Thank you again for your help.

**Comment by rvolden** [comment]
If it doesn't have the coverage in the name, this version of Mandalorion won't work. You can try my PI's version here: https://github.com/christopher-vollmers/Mandalorion-Episode-II
