### ISSUE TITLE
Error regarding nanopore 1D reads

### ISSUE THREAD

**Issue by ashokpatowary** [rvolden/Mandalorion-Episode-II#7]
Hi @rvolden ,

I was trying to used the modified code pulled from yours. But I didnot find to report the issue in that page so reporting it to you.

While I was running the code for MinION 1D reads, I came across the following error. 

> /u/local/apps/python/3.6.1/lib/python3.6/site-packages/numpy-1.12.1-py3.6-linux-x86_64.egg/numpy/core/fromnumeric.py:2889: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/u/local/apps/python/3.6.1/lib/python3.6/site-packages/numpy-1.12.1-py3.6-linux-x86_64.egg/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
rm: cannot remove `/u/home/a/MinION/Run_04_Part/parsed_reads/*': No such file or directory
Traceback (most recent call last):
  File "defineAndQuantifyIsoforms.py", line 245, in <module>
    main()
  File "defineAndQuantifyIsoforms.py", line 242, in main
    define_start_end_sites(start_end_dict, individual_path, subreads)
  File "defineAndQuantifyIsoforms.py", line 181, in define_start_end_sites
    + filename + '.fasta', 'a')
OSError: [Errno 31] Too many links: '/u/home/a/MinION/Run_04_Part/parsed_reads/Isoform25001.fasta'
Traceback (most recent call last):
  File "createConsensi.py", line 70, in <module>
    progs = configReader(args['config'])
  File "createConsensi.py", line 50, in configReader
    raise Exception('Check config file')
Exception: Check config file
Traceback (most recent call last):
  File "filterIsoforms.py", line 42, in <module>
    isoforms = read_fasta(infile)
  File "filterIsoforms.py", line 24, in read_fasta
    for line in open(inFile):
FileNotFoundError: [Errno 2] No such file or directory: '/u/home/a/MinION/Run_04_Part/Isoform_Consensi.fasta'

bed file was generated; parsed_read folder was also generated and I can see the isoform fasta filed in the folder. But I fail to understand what this error is.
Thanks

**Comment by rvolden** [comment]
To me it looks like the program is trying to put too many files into one directory (Error 31: too many links). Currently working on a fix that puts isoforms into subdirectories, which should circumvent (hopefully) the 32000 file limit.

**Comment by ashokpatowary** [comment]
@rvolden 

Thanks for the response. Presently I am working on a small dtatset (~25% of the fastq generated in the run). Do, you have any quick suggestion like working on with subset of the gtf file for now so that I can run the pipeline? 

Thanks

**Comment by rvolden** [comment]
Working on a subset of the gtf file would be fine, but you might find it useful to group together by the transcript ID before subsampling your file so you don't lose information on the reads you end up with
